version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: false
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-71
  brakeman:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "node_modules/"
  - "script/"
  - "spec/"
  - "test/"
  - "tests/"
  - "vendor/"
  - "lib/tasks/"
  - "app/assets/javascripts/lib/"
  - "bin/"
  - "**/__tests__/"
  - "**/.eslintrc.js"
  - "*.js"
