image:
  file: .gitpod.dockerfile

ports:
  - port: 3000
    onOpen: ignore
  - port: 3035
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore

tasks:
  - name: Forem Server
    before: |
      redis-server &
    init: >
      cp .env_sample .env &&
      echo "APP_DOMAIN=\"$(gp url 3000 | cut -f 3 -d /)\"" >> .env &&
      echo 'APP_PROTOCOL="https://"' >> .env &&
      gem install solargraph &&
      gem install foreman &&
      bin/setup
    command: >
      bin/startup
  - command: >
      gp await-port 3000 &&
      printf "Waiting for Forem server ..." &&
      until $(curl -sNL $(gp url 3000) | grep -q "DEV"); do printf '.'; sleep 5; done && echo "" &&
      gp preview $(gp url 3000)

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
    # add a check to pull requests (defaults to true)
    addCheck: true
