experiments:
  user_home_feed: # Home feed collection for logged in user
    variants:
      - more_comments_minimal_weight_randomized_at_end
    weights:
      - 100
    goals:
      - user_creates_comment
      - user_creates_reaction
      - user_views_article_four_days_in_week
      - user_views_article_four_hours_in_day
  follow_implicit_points: # Points given for implicit tag weights
    # Implemented here: app/workers/follows/update_points_worker.rb
    # Hypotheses: Weighting tags based on implied preference will lead
    # to more repeat engagement.
    # Recommended duration: 4 weeks (ending at start of January)
    variants:
      - base
      - no_implicit_score
      - half_weight_after_log
      - double_weight_after_log
      - double_bonus_before_log
      - without_weighting_bonus
    weights: # "base" (what we currently implement) and "no_implicit_score" are what we want the most data on.
      - 30
      - 30
      - 10
      - 10
      - 10
      - 10
    goals:
      - user_creates_comment
      - user_creates_reaction
      - user_views_article_four_days_in_week
      - user_views_article_four_hours_in_day
exclude:
  bots: true

# Dashboard performance
cache: true

# For logged-in users we'll explicitely pass participant.
# If we experiment on non-logged in, we don't want to collect cookies anyway.
cookies: false
