experiments:
  user_home_feed: # Home feed collection for logged in user
    variants:
      - more_comments_minimal_weight_randomized_at_end
    weights:
      - 100
    goals:
      - user_creates_comment
      - user_creates_reaction
      - user_views_article_four_days_in_week
      - user_views_article_four_hours_in_day
exclude:
  bots: true

# Dashboard performance
cache: true

# For logged-in users we'll explicitely pass participant.
# If we experiment on non-logged in, we don't want to collect cookies anyway.
cookies: false
