display_sponsors:
  cast_type: boolean
  value: false
  description: "Home page sponsor display"
live_starting_soon:
  cast_type: boolean
  value: false
  description: "/live event is starting soon."
live_is_live:
  cast_type: boolean
  value: false
  description: "/live page showing live event"
she_coded:
  cast_type: boolean
  value: false
  description: "Toggle #shecoded sidebar"
upcoming_events:
  cast_type: boolean
  value: true
  description: "Toggle upcoming events in sidebar"
