# This is a sample application.yml
#
# If you wish to use this, please copy this file and rename it  to application.yml
# For questions or concerns, please submit an issue!

################################################
############## Basic configuration #############
################################################

# App damain + Protocol setting for development
APP_DOMAIN: "localhost:3000"
APP_PROTOCOL: "http://"

# Default staff account's id
DEVTO_USER_ID: "1"

# Service timeout length
SERVICE_TIMEOUT: "100000"

# Production related config that can be ignored
DEPLOYMENT_SIGNATURE: "PLACEHOLDER"

################################################
############## 3rd Party Services ##############
################################################

# It's best if you have the following configured
# for more development experience

# Github for github related access
GITHUB_KEY: "REPLACEME"
GITHUB_SECRET: "REPLACEME"
GITHUB_TOKEN: "REPLACEME"

# Twitter for normal twitter access
TWITTER_ACCESS_TOKEN: "REPLACEME"
TWITTER_ACCESS_TOKEN_SECRET: "REPLACEME"
TWITTER_KEY: "REPLACEME"
TWITTER_SECRET: "REPLACEME"

################################################
######### Optional 3rd Party Services ##########
################################################

# They are very optional

# Airbrake for error tracking
AIRBRAKE_API_KEY: "REPLACEME"
AIRBRAKE_PROJECT_ID: "REPLACEME"

# Algolish for search
ALGOLIASEARCH_API_KEY: "REPLACEME"
ALGOLIASEARCH_APPLICATION_ID: "REPLACEME"
ALGOLIASEARCH_SEARCH_ONLY_KEY: "REPLACEME"

# AWS for images storages
AWS_DEFAULT_REGION: "REPLACEME"
AWS_SDK_KEY: "REPLACEME"
AWS_SDK_SECRET: "REPLACEME"

# AWS for video storage
AWS_S3_VIDEO_ID: "REPLACEME"
AWS_S3_VIDEO_KEY: "REPLACEME"
AWS_S3_INPUT_BUCKET: "REPLACEME"
AWS_S3_VIDEO_ID: "REPLACEME"
AWS_S3_VIDEO_KEY: "REPLACEME"
AWS_SDK_KEY: "REPLACEME"
AWS_SDK_SECRET: "REPLACEME"
AWS_SECRET: "REPLACEME"


# Buffer for sending to buffer
BUFFER_ACCESS_TOKEN: "REPLACEME"
BUFFER_FACEBOOK_ID: "REPLACEME"
BUFFER_LINKEDIN_ID: "REPLACEME"
BUFFER_PROFILE_ID: "REPLACEME"
BUFFER_TWITTER_ID: "REPLACEME"

# Cloudinary for image resizing and cache??
CLOUDINARY_API_KEY: "REPLACEME"
CLOUDINARY_API_SECRET: "REPLACEME"
CLOUDINARY_CLOUD_NAME: "REPLACEME"
CLOUDINARY_SECURE: "REPLACEME"

# Dacast for streaming
DACAST_STREAM_CODE: "REPLACEME"

# Google analytic
GA_SERVICE_ACCOUNT_JSON: "REPLACEME"
GA_TRACKING_ID: "REPLACEME"
GA_VIEW_ID: "REPLACEME"
GA_OPTIMIZE_ID: "REPLACEME"

# JW player for videos on the site
JWPLAYER_API_KEY: "REPLACEME"
JWPLAYER_API_SECRET: "REPLACEME"

# Mailchimp for mails
MAILCHIMP_API_KEY: "REPLACEME"
MAILCHIMP_NEWSLETTER_ID: "REPLACEME"
MAILCHIMP_SUSTAINING_MEMBERS_ID: "REPLACEME"

# Google recaptcha
RECAPTCHA_SECRET: "REPLACEME"
RECAPTCHA_SITE: "REPLACEME"

# Sharemeow is a text-shot service
# more information here https://github.com/producthunt/ShareMeow
SHARE_MEOW_BASE_URL: "REPLACEME"
SHARE_MEOW_SECRET_KEY: "REPLACEME"

# Slack for customer alerts
SLACK_CHANNEL: "REPLACEME"
SLACK_WEBHOOK_URL: "REPLACEME"

# Stream for notifications
STREAM_RAILS_KEY: "REPLACEME"
STREAM_RAILS_SECRET: "REPLACEME"
STREAM_URL: "REPLACEME"

# Stripe for payment system
STRIPE_PUBLISHABLE_KEY: "REPLACEME"
STRIPE_SECRET_KEY: "REPLACEME"

#Email digest frequency
PERIODIC_EMAIL_DIGEST_MAX: 10
PERIODIC_EMAIL_DIGEST_MIN: 2

#Pusher for DEV Connect/notfications
PUSHER_APP_ID: "REPLACEME"
PUSHER_CLUSTER: "REPLACEME"
PUSHER_KEY: "REPLACEME"
PUSHER_SECRET: "REPLACEME"

#For video calling in DEV Connect
TWILIO_ACCOUNT_SID: "REPLACEME"
TWILIO_VIDEO_API_KEY: "REPLACEME"
TWILIO_VIDEO_API_SECRET: "REPLACEME"

#For browser webpush notifications (webpush gem) (totally random base64 nums)
VAPID_PUBLIC_KEY: "dGhpcyBpcyBkZXYudG8gdGVzdCBkYXRh"
VAPID_PRIVATE_KEY: "VGhpcyBpcyBtb3JlIHRlc3QgZGF0YQ=="
