log_worker_queue_stats:
  cron: "*/10 * * * *" # every 10 minutes
  class: "Metrics::RecordBackgroundQueueStatsWorker"
record_daily_usage:
  cron: "0 11 * * *" # daily at 11:00 UTC
  class: "Metrics::RecordDailyUsageWorker"
record_daily_notifications:
  cron: "0 11 * * *" # daily at 11:00 UTC
  class: "Metrics::RecordDailyNotificationsWorker"
record_data_counts:
  cron: "10 * * * *" # every hour, 10 min after the hour
  class: "Metrics::RecordDataCountsWorker"
award_yearly_club_badges:
  cron: "0 0 * * *" # daily at 12 am UTC
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_yearly_club_badges
    - ""
award_beloved_comment_badges:
  cron: "5 */12 * * *" # 5 min past every 12th hour UTC
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_beloved_comment_badges
    - ""
award_four_week_streak_badge:
  cron: "10 */12 * * *" # 10 min past every 12th hour UTC
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_four_week_streak_badge
    - ""
award_eight_week_streak_badge:
  cron: "15 */12 * * *" # 15 min past every 12th hour UTC
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_eight_week_streak_badge
    - ""
award_sixteen_week_streak_badge:
  cron: "20 */12 * * *" # 20 min past every 12th hour UTC
  class: "BadgeAchievements::BadgeAwardWorker"
  args:
    - ""
    - award_sixteen_week_streak_badge
    - ""
