[build]
  command = "make"
  [environment]
    NETLIFY_USE_YARN = 1

# See <https://docs.netlify.com/routing/redirects/redirect-options/> for more options
[[redirects]]
from = "https://docs.dev.to"
to = "https://docs.forem.com"
status = 301
force = true

[[redirects]]
from = "https://docs.dev.to/*"
to = "https://docs.forem.com/:splat"
status = 301
force = true
