name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: >
          Thank you so much for your PR! We'll do our best to review your submission as soon as possible.

          If you don't hear from us within 3 business days, please ping @thepracticaldev/oss.

          Some things we look for immediately when reviewing a PR are: tests, updated docs, etc.

          Please make sure you've added all relevant info in order to help us get your code merged as quickly as possible!
