# This workflow allows an organization member or owner to kickoff an automated
# rebase by commenting on a pull request with "/rebase". In order for the
# workflow to run, organization membership must be set to public!

# https://github.com/marketplace/actions/automatic-rebase (https://github.com/cirrus-actions/rebase)

on:
  issue_comment:
    types: [created]
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: contains(github.event.comment.html_url, '/pull/') &&
      startsWith(github.event.comment.body, '/rebase') &&
      (github.event.comment.author_association == 'MEMBER' ||
      github.event.comment.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
